# Generated by Django 4.2.13 on 2024-12-31 13:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('StoryTeller', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='AboutMe',
            new_name='User',
        ),
    ]
